MotChallenge2DBox
/home/ogam3080/cagri/mot/SUSHI/output/experiments/mot17_public_train_07-08_21:36:06.122947/oracle
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ogam3080/miniconda3/envs/py_cuda/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/ogam3080/miniconda3/envs/py_cuda/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/ogam3080/cagri/mot/SUSHI/TrackEval/trackeval/_timing.py", line 64, in wrap
    return f(*args, **kw)
  File "/home/ogam3080/cagri/mot/SUSHI/TrackEval/trackeval/eval.py", line 191, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq)
  File "/home/ogam3080/cagri/mot/SUSHI/TrackEval/trackeval/_timing.py", line 64, in wrap
    return f(*args, **kw)
  File "/home/ogam3080/cagri/mot/SUSHI/TrackEval/trackeval/datasets/_base_dataset.py", line 92, in get_raw_seq_data
    raw_gt_data = self._load_raw_file(tracker, seq, is_gt=True)
  File "/home/ogam3080/cagri/mot/SUSHI/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 228, in _load_raw_file
    time_data = np.asarray(read_data[time_key], dtype=np.float)
  File "/home/ogam3080/miniconda3/envs/py_cuda/lib/python3.9/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ogam3080/cagri/mot/SUSHI/TrackEval/trackeval/eval.py", line 81, in evaluate
    results = pool.map(_eval_sequence, seq_list)
  File "/home/ogam3080/miniconda3/envs/py_cuda/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/ogam3080/miniconda3/envs/py_cuda/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations





